Repository ajaykrish244/ScheduleBot, pull requests merged in 2023-11, with the labels that each got.

#6 Hotfix for bug
  src/functionality/shared_functions.py
Labels: bug

#15 Feature/quick schedule
  src/functionality/quick_schedule.py
  src/schedulebot.py
Labels: enhancement

#22 Docs/update readme
  README.md
  src/schedulebot.py
Labels: documentation

#23 Added support for quicksched slash command
  src/functionality/quick_schedule.py
  src/schedulebot.py
Labels: enhancement
